# Generated by Django 4.0.4 on 2022-04-15 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_postcategory_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='raiting',
            new_name='rating',
        ),
    ]
