# Generated by Django 4.0.4 on 2022-05-11 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_subscriber_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriber',
            name='mail',
            field=models.EmailField(max_length=254),
        ),
    ]
